/* ==========================================================
   GENERADOR DE RENAMES PARA ESQUEMA DELASSMVP
   Crea:  C:\SPOOLTEST\run_renames_DELASSMVP.sql
   ========================================================== */
SET TERMOUT OFF
SET HEADING OFF
SET FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 200

SPOOL C:/SPOOLTEST/run_renames_DELASSMVP.sql

PROMPT -- Renombrar tabla CLIENT → BORROWER
SELECT 'ALTER TABLE DELASSMVP.CLIENT RENAME TO BORROWER;' FROM dual;
PROMPT

PROMPT -- Renombrar columnas de la nueva tabla BORROWER
SELECT 'ALTER TABLE DELASSMVP.BORROWER RENAME COLUMN CLIENT_CLASSIFICATION TO BORROWER_CLASSIFICATION;' FROM dual;
SELECT 'ALTER TABLE DELASSMVP.BORROWER RENAME COLUMN CLIENT_EMPLOYMENT_STATUS TO BORROWER_EMPLOYMENT_STATUS;' FROM dual;
SELECT 'ALTER TABLE DELASSMVP.BORROWER RENAME COLUMN CLIENT_ID TO BORROWER_ID;' FROM dual;
SELECT 'ALTER TABLE DELASSMVP.BORROWER RENAME COLUMN CLIENT_IDENTIFICATION_DATE TO BORROWER_IDENTIFICATION_DATE;' FROM dual;
PROMPT

PROMPT -- Renombrar columna en la tabla CONTRACT (y FK si procede)
SELECT 'ALTER TABLE DELASSMVP.CONTRACT RENAME COLUMN CLIENT_ID TO BORROWER_ID;' FROM dual;
PROMPT

/* --- (Opcional) recompilar todo el esquema para dejar todo VALID --- */
SELECT 'BEGIN DBMS_UTILITY.compile_schema(schema=>''DELASSMVP''); END; /' FROM dual;

SPOOL OFF
SET TERMOUT ON
PROMPT === Guion listo:  C:\SPOOLTEST\run_renames_DELASSMVP.sql  ===
